### ISSUE TITLE
Cannot open input file 'Galaxy.lib'

### ISSUE THREAD

**Issue by ajrdesign** [GameMakerDiscord/GOG.gml#2]
I got the structure of the projects right now but i still cant build. I get the very short error 

`LNK1181	cannot open input file 'Galaxy.lib'	

Ive looked through the code for any mention of "Galaxy.lib" and ive looked through all files for such a file but i dont know what it is. Im using VS2019. I tried also using VS2015 after installing and updating it but it gives another error even before building because it needs v142 build tools that if i understand correctly doesnt exist for 2015. Any tips?

_Originally posted by @Lautaro in https://github.com/GameMakerDiscord/GOG.gml/issues/1#issuecomment-1036650357_

Having the same issue highlighted in the other post.

**Comment by YellowAfterlife** [comment]
As of the current GameMaker versions you should be using [the official extension](https://github.com/YoYoGames/GMEXT-GOG) that borrows a handful of code from this one

**Comment by ajrdesign** [comment]
Ahh I did not know that existed. Thank you! I think GOG needs to update their documentation cause they are still pointing to this repo.
